# PyTorch Tensors

- This tutorial briefly describes some basic operations on Tensors in PyTorch. 
- This [documentation](http://pytorch.org/docs/master/torch.html) from pytorch contains information about all the possible operations on Tensors.

In [1]:
import torch
import torch.nn as nn
import numpy as np

## Getting started with Tensors

### Creating a Tensor

In [2]:
#Create Torch Tensor from a list
x = torch.Tensor([[1,2,3],[4,5,6]])
print (x) # prints the tensor
print ('shape: ',x.shape) # returns the shape of the tensor. You can also use x.size()

tensor([[1., 2., 3.],
        [4., 5., 6.]])
shape:  torch.Size([2, 3])


- you can use the `.numpy()` function to obtain the numpy array from tensor.

In [3]:
print ('numpy array: ')
print (x.numpy()) # obtains the numpy array from the pytorch Tensor

numpy array: 
[[1. 2. 3.]
 [4. 5. 6.]]


- The default `torch.Tensor` is a float tensor as you can see above.
- You can use `torch.LongTensor` for tensor of integer types.

In [4]:
x = torch.LongTensor([1,4,6])
print (x) # prints the tensor
print ('shape: ', x.shape) # returns the shape of the tensor. You can also use x.size()
print ('numpy array: ',x.numpy()) #obtains the numpy array

tensor([1, 4, 6])
shape:  torch.Size([3])
numpy array:  [1 4 6]


- You can also create Tensors from numpy arrays

In [5]:
one_arr = np.ones(5) # a numpy array
print (one_arr)

[1. 1. 1. 1. 1.]


In [6]:
x = torch.from_numpy(one_arr)
print (x) 
print (x.shape) #obtains the shape of the tensor

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
torch.Size([5])


In [7]:
print (x.numpy()) #obtains the numpy array from the Tensor

[1. 1. 1. 1. 1.]


### Indexing into a Tensor

In [8]:
a = np.random.rand(3,4,5)
x = torch.from_numpy(a)
print (x)
print ('shape: ',x.shape)

tensor([[[0.0809, 0.4367, 0.6641, 0.4338, 0.8787],
         [0.0433, 0.8233, 0.3377, 0.2330, 0.6928],
         [0.1616, 0.9488, 0.6204, 0.1012, 0.2346],
         [0.1245, 0.2163, 0.0655, 0.3716, 0.7432]],

        [[0.4204, 0.5892, 0.2297, 0.6034, 0.9370],
         [0.0300, 0.7340, 0.4687, 0.4151, 0.0618],
         [0.0802, 0.8095, 0.2518, 0.8315, 0.8113],
         [0.0262, 0.6908, 0.3657, 0.2320, 0.4136]],

        [[0.1431, 0.0068, 0.0795, 0.1329, 0.6936],
         [0.5587, 0.9627, 0.2118, 0.7177, 0.8933],
         [0.2874, 0.6682, 0.4687, 0.0898, 0.7850],
         [0.3599, 0.6922, 0.1876, 0.8982, 0.1550]]], dtype=torch.float64)
shape:  torch.Size([3, 4, 5])


In [9]:
# you can index into them like arrays
print (x[0]) #gives you a matrix Tensor
print (x[0].shape)

tensor([[0.0809, 0.4367, 0.6641, 0.4338, 0.8787],
        [0.0433, 0.8233, 0.3377, 0.2330, 0.6928],
        [0.1616, 0.9488, 0.6204, 0.1012, 0.2346],
        [0.1245, 0.2163, 0.0655, 0.3716, 0.7432]], dtype=torch.float64)
torch.Size([4, 5])


In [10]:
# you can index into them like arrays
print (x[0][2]) # gives you a vector Tensor
print (x[0][2].shape)

tensor([0.1616, 0.9488, 0.6204, 0.1012, 0.2346], dtype=torch.float64)
torch.Size([5])


In [14]:
print (x[0][2][3].item()) #this gives you a scalar Python number

0.10116234706752503


### Reshaping a Tensor

- To reshape a tensor to a different size, you can use the `.view()` function. 
- The `.view()` function returns a tensor with the same data as the self tensor but of a different size

In [15]:
a = np.random.rand(2,6)
x = torch.from_numpy(a)
print (x)
print ('shape: ',x.shape)

tensor([[0.3254, 0.8644, 0.2688, 0.4030, 0.9252, 0.9207],
        [0.6507, 0.8194, 0.4609, 0.2892, 0.3176, 0.5650]], dtype=torch.float64)
shape:  torch.Size([2, 6])


In [16]:
y = x.view(3,4) #reshapes it into a tensor of size 3 x 4
print (y)
print (y.shape)

tensor([[0.3254, 0.8644, 0.2688, 0.4030],
        [0.9252, 0.9207, 0.6507, 0.8194],
        [0.4609, 0.2892, 0.3176, 0.5650]], dtype=torch.float64)
torch.Size([3, 4])


In [17]:
y = x.view(2,3,2) #reshapes the tensor into 2 x 3 x 2
print (y)
print (y.shape)

tensor([[[0.3254, 0.8644],
         [0.2688, 0.4030],
         [0.9252, 0.9207]],

        [[0.6507, 0.8194],
         [0.4609, 0.2892],
         [0.3176, 0.5650]]], dtype=torch.float64)
torch.Size([2, 3, 2])


- if one of the dimensions is `-1`, as shown below, then its size can be inferred. So, you cannot have multiple -1's in view.

In [18]:
y = x.view(4,3) #reshapes the tensor into 4x3
print (y)
print (y.shape)

tensor([[0.3254, 0.8644, 0.2688],
        [0.4030, 0.9252, 0.9207],
        [0.6507, 0.8194, 0.4609],
        [0.2892, 0.3176, 0.5650]], dtype=torch.float64)
torch.Size([4, 3])


In [19]:
y = x.view(4,-1) #same as above, but the second dimension can be inferred.
print (y)
print (y.shape)

tensor([[0.3254, 0.8644, 0.2688],
        [0.4030, 0.9252, 0.9207],
        [0.6507, 0.8194, 0.4609],
        [0.2892, 0.3176, 0.5650]], dtype=torch.float64)
torch.Size([4, 3])


### Operations on Tensors

- You can do some basic operations on tensors like arrays

In [20]:
a = np.random.rand(1,5)
x = torch.from_numpy(a)
print (x)
print (x.shape)

tensor([[0.5227, 0.9553, 0.7359, 0.4028, 0.3062]], dtype=torch.float64)
torch.Size([1, 5])


In [21]:
b = np.ones((1,5))
y = torch.from_numpy(b)
print (y)
print (y.shape)

tensor([[1., 1., 1., 1., 1.]], dtype=torch.float64)
torch.Size([1, 5])


In [22]:
print (x + y) #element wise addition

tensor([[1.5227, 1.9553, 1.7359, 1.4028, 1.3062]], dtype=torch.float64)


In [23]:
print (x - y) #element wise subtraction

tensor([[-0.4773, -0.0447, -0.2641, -0.5972, -0.6938]], dtype=torch.float64)


In [24]:
print (x * y)  #element wise multiplication

tensor([[0.5227, 0.9553, 0.7359, 0.4028, 0.3062]], dtype=torch.float64)


- Another useful operation on tensors is concatenation.
- You can use the `torch.cat()` function, it takes in a list/sequence of tensors and concatenates them

In [25]:
torch.cat([x,y]) # concatenates them along the row (dim=0) by default.

tensor([[0.5227, 0.9553, 0.7359, 0.4028, 0.3062],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]], dtype=torch.float64)

In [26]:
torch.cat([x,y], dim=1) # concatenates them along the column when dim=1 is mentioned.

tensor([[0.5227, 0.9553, 0.7359, 0.4028, 0.3062, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]], dtype=torch.float64)

- If you want to expand a Tensor along the singleton dimension, you can use the `.expand()` function.

In [27]:
x = torch.Tensor([[1],[2],[3]])
print (x)
print (x.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [28]:
x.expand(3,4) #expands it along the second dimension from (3 x 1) to be (3 x 4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [29]:
x = torch.Tensor([5,6]).view(-1,2) #reshaping it to 1 x 2
x.expand(5,2) #expands it along the first dimension from (1 x 2) to (5 x 2)

tensor([[5., 6.],
        [5., 6.],
        [5., 6.],
        [5., 6.],
        [5., 6.]])

- These are the basic operations on the Tensors that will be very useful. You can check the [documentation here](http://pytorch.org/docs/master/torch.html) for all list of operations.